package com.xquadro.android.alieninvaders.levels;

import com.badlogic.gdx.utils.Array;
import com.xquadro.android.alieninvaders.levels.Level.Difficulty;
import com.xquadro.android.alieninvaders.levels.Level.LevelName;
import com.xquadro.android.alieninvaders.settings.Player;

public class Levels {
	public Array<Level> levels;
	//private Array<Level> levels;

	public Array<Level> getLevels() {
		return levels;
	}

	public Levels() {
		super();
		levels = new Array<Level>();
	}

	public void loadLevels() {
		Level level = new Level();
		level.setLevelName(LevelName.SUN);
		level.setName("Sun");
		level.setPositionX(0.79f);
		level.setPositionY(0.46f);
		level.setEarth(true);
		level.setCountAlienKamikaze(0);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(0);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		//easy
		level = new Level();
		level.setLevelName(LevelName.BETA_CENTAURI);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Beta Centauri");
		level.setPositionX(0.7832848f);
		level.setPositionY(0.5315529f);
		level.setEarth(false);
		level.setCountAlienKamikaze(4);
		level.setCountAlienFighter(3);
		level.setCountAlienCorvette(5);
		level.setCountAlienDestroyer(2);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.PROCYON);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Procyon");
		level.setPositionX(0.76128066f);
		level.setPositionY(0.5915735f);
		level.setEarth(false);
		level.setCountAlienKamikaze(0);
		level.setCountAlienFighter(14);
		level.setCountAlienCorvette(6);
		level.setCountAlienDestroyer(7);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.ALTAIR);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Altair");
		level.setPositionX(0.65915895f);
		level.setPositionY(0.42491537f);
		level.setEarth(false);
		level.setCountAlienKamikaze(4);
		level.setCountAlienFighter(4);
		level.setCountAlienCorvette(4);
		level.setCountAlienDestroyer(4);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.ELNATH);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Elnath");
		level.setPositionX(0.7125575f);
		level.setPositionY(0.52047163f);
		level.setEarth(false);
		level.setCountAlienKamikaze(13);
		level.setCountAlienFighter(2);
		level.setCountAlienCorvette(2);
		level.setCountAlienDestroyer(2);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.NAOS);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Naos");
		level.setPositionX(0.92362547f);
		level.setPositionY(0.59397733f);
		level.setEarth(false);
		level.setCountAlienKamikaze(7);
		level.setCountAlienFighter(4);
		level.setCountAlienCorvette(4);
		level.setCountAlienDestroyer(2);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(9);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.ALCHIBA);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Alchiba");
		level.setPositionX(0.65346545f);
		level.setPositionY(0.4903245f);
		level.setEarth(false);
		level.setCountAlienKamikaze(8);
		level.setCountAlienFighter(2);
		level.setCountAlienCorvette(10);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(9);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.SYRMA);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Syrma");
		level.setPositionX(0.73197633f);
		level.setPositionY(0.46130112f);
		level.setEarth(false);
		level.setCountAlienKamikaze(1);
		level.setCountAlienFighter(3);
		level.setCountAlienCorvette(6);
		level.setCountAlienDestroyer(5);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		
		level = new Level();
		level.setLevelName(LevelName.TARAZED);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Tarazed");
		level.setPositionX(0.8484695f);
		level.setPositionY(0.5273058f);
		level.setEarth(false);
		level.setCountAlienKamikaze(6);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(3);
		level.setCountAlienDestroyer(3);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(2);
		level.setCountAlienHeavyCruiser(2);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.ALKALUROPS);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Alkalurops");
		level.setPositionX(0.86016715f);
		level.setPositionY(0.6058155f);
		level.setEarth(false);
		level.setCountAlienKamikaze(3);
		level.setCountAlienFighter(3);
		level.setCountAlienCorvette(4);
		level.setCountAlienDestroyer(8);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(1);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.AVIOR);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Avior");
		level.setPositionX(0.663972f);
		level.setPositionY(0.55495536f);
		level.setEarth(false);
		level.setCountAlienKamikaze(5);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(9);
		level.setCountAlienDestroyer(3);
		level.setCountAlienFrigate(6);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.MIRA);
		level.setDifficulty(Difficulty.EASY);
		level.setName("Mira");
		level.setPositionX(0.81206656f);
		level.setPositionY(0.57882214f);
		level.setEarth(false);
		level.setCountAlienKamikaze(7);
		level.setCountAlienFighter(1);
		level.setCountAlienCorvette(8);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(2);
		level.setCountAlienLightCruiser(2);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(1);
		levels.add(level);
		
		//medium
		
		level = new Level();
		level.setLevelName(LevelName.CAPELLA);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Capella");
		level.setPositionX(0.6049467f);
		level.setPositionY(0.38588813f);
		level.setEarth(false);
		level.setCountAlienKamikaze(2);
		level.setCountAlienFighter(3);
		level.setCountAlienCorvette(3);
		level.setCountAlienDestroyer(4);
		level.setCountAlienFrigate(5);
		level.setCountAlienLightCruiser(4);
		level.setCountAlienHeavyCruiser(1);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(1);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.REGEL);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Regel");
		level.setPositionX(0.51494056f);
		level.setPositionY(0.5485542f);
		level.setEarth(false);
		level.setCountAlienKamikaze(3);
		level.setCountAlienFighter(7);
		level.setCountAlienCorvette(0);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(4);
		level.setCountAlienLightCruiser(5);
		level.setCountAlienHeavyCruiser(6);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(3);
		level.setCountAlienDreadnought(1);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.ACHERNAR);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Achernar");
		level.setPositionX(0.51636696f);
		level.setPositionY(0.44315773f);
		level.setEarth(false);
		level.setCountAlienKamikaze(3);
		level.setCountAlienFighter(3);
		level.setCountAlienCorvette(1);
		level.setCountAlienDestroyer(4);
		level.setCountAlienFrigate(6);
		level.setCountAlienLightCruiser(7);
		level.setCountAlienHeavyCruiser(7);
		level.setCountAlienBattleCruiser(2);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.ALDEBARAN);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Aldebaran");
		level.setPositionX(0.53176427f);
		level.setPositionY(0.62408406f);
		level.setEarth(false);
		level.setCountAlienKamikaze(0);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(6);
		level.setCountAlienDestroyer(5);
		level.setCountAlienFrigate(5);
		level.setCountAlienLightCruiser(9);
		level.setCountAlienHeavyCruiser(5);
		level.setCountAlienBattleCruiser(2);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(1);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.FOMALHAUT);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Fomalhaut");
		level.setPositionX(0.791301f);
		level.setPositionY(0.6533162f);
		level.setEarth(false);
		level.setCountAlienKamikaze(0);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(1);
		level.setCountAlienDestroyer(8);
		level.setCountAlienFrigate(9);
		level.setCountAlienLightCruiser(10);
		level.setCountAlienHeavyCruiser(7);
		level.setCountAlienBattleCruiser(3);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(1);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.ALPHA_CRUCIS);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Alpha Crucis");
		level.setPositionX(0.6278716f);
		level.setPositionY(0.5685563f);
		level.setEarth(false);
		level.setCountAlienKamikaze(0);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(9);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(10);
		level.setCountAlienLightCruiser(7);
		level.setCountAlienHeavyCruiser(1);
		level.setCountAlienBattleCruiser(2);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.BETA_CRUCIS);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Beta_Crucis");
		level.setPositionX(0.3104711f);
		level.setPositionY(0.39860198f);
		level.setEarth(false);
		level.setCountAlienKamikaze(10);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(7);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(14);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(1);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.GRAFIAS);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Grafias");
		level.setPositionX(0.72831804f);
		level.setPositionY(0.7135533f);
		level.setEarth(false);
		level.setCountAlienKamikaze(5);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(5);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(15);
		level.setCountAlienHeavyCruiser(10);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(1);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.MARFAK);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Marfak");
		level.setPositionX(0.6679213f);
		level.setPositionY(0.66646296f);
		level.setEarth(false);
		level.setCountAlienKamikaze(4);
		level.setCountAlienFighter(1);
		level.setCountAlienCorvette(6);
		level.setCountAlienDestroyer(1);
		level.setCountAlienFrigate(9);
		level.setCountAlienLightCruiser(7);
		level.setCountAlienHeavyCruiser(1);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(1);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.SEGIN);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Segin");
		level.setPositionX(0.81667465f);
		level.setPositionY(0.73745066f);
		level.setEarth(false);
		level.setCountAlienKamikaze(5);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(1);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(10);
		level.setCountAlienLightCruiser(15);
		level.setCountAlienHeavyCruiser(7);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(1);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.CANOPUS);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Canopus");
		level.setPositionX(0.46788836f);
		level.setPositionY(0.6270322f);
		level.setEarth(false);
		level.setCountAlienKamikaze(10);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(14);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(5);
		level.setCountAlienLightCruiser(8);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(0);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.THABIT);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Thabit");
		level.setPositionX(0.9446545f);
		level.setPositionY(0.65725553f);
		level.setEarth(false);
		level.setCountAlienKamikaze(5);
		level.setCountAlienFighter(1);
		level.setCountAlienCorvette(13);
		level.setCountAlienDestroyer(2);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(2);
		level.setCountAlienHeavyCruiser(10);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(2);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.TEGMINE);
		level.setDifficulty(Difficulty.MEDIUM);
		level.setName("Tegmine");
		level.setPositionX(0.5669699f);
		level.setPositionY(0.5875904f);
		level.setEarth(false);
		level.setCountAlienKamikaze(9);
		level.setCountAlienFighter(3);
		level.setCountAlienCorvette(12);
		level.setCountAlienDestroyer(1);
		level.setCountAlienFrigate(13);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(2);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(1);
		levels.add(level);

		//hard
		level = new Level();
		level.setLevelName(LevelName.SIRIUS);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Sirius");
		level.setPositionX(0.25088578f);
		level.setPositionY(0.508032f);
		level.setEarth(false);
		level.setCountAlienKamikaze(9);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(12);
		level.setCountAlienDestroyer(1);
		level.setCountAlienFrigate(11);
		level.setCountAlienLightCruiser(1);
		level.setCountAlienHeavyCruiser(12);
		level.setCountAlienBattleCruiser(4);
		level.setCountAlienBattleShip(2);
		level.setCountAlienDreadnought(10);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.ALPHA_CENTAURI);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Alpha Centauri");
		level.setPositionX(0.1550711f);
		level.setPositionY(0.4046872f);
		level.setEarth(false);
		level.setCountAlienKamikaze(0);
		level.setCountAlienFighter(8);
		level.setCountAlienCorvette(5);
		level.setCountAlienDestroyer(2);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(14);
		level.setCountAlienHeavyCruiser(1);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(5);
		level.setCountAlienDreadnought(5);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.VEGA);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Vega");
		level.setPositionX(0.21048686f);
		level.setPositionY(0.4200312f);
		level.setEarth(false);
		level.setCountAlienKamikaze(9);
		level.setCountAlienFighter(1);
		level.setCountAlienCorvette(13);
		level.setCountAlienDestroyer(5);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(5);
		level.setCountAlienHeavyCruiser(8);
		level.setCountAlienBattleCruiser(9);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(7);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.ADHAFERA);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Adhafera");
		level.setPositionX(0.32723978f);
		level.setPositionY(0.5133983f);
		level.setEarth(false);
		level.setCountAlienKamikaze(14);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(13);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(8);
		level.setCountAlienLightCruiser(13);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(12);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(8);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.BETELGEUSE);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Betelgeuse");
		level.setPositionX(0.42817667f);
		level.setPositionY(0.5582621f);
		level.setEarth(false);
		level.setCountAlienKamikaze(14);
		level.setCountAlienFighter(6);
		level.setCountAlienCorvette(0);
		level.setCountAlienDestroyer(9);
		level.setCountAlienFrigate(11);
		level.setCountAlienLightCruiser(13);
		level.setCountAlienHeavyCruiser(7);
		level.setCountAlienBattleCruiser(4);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(12);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.SPICA);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Spica");
		level.setPositionX(0.38365582f);
		level.setPositionY(0.2866536f);
		level.setEarth(false);
		level.setCountAlienKamikaze(3);
		level.setCountAlienFighter(14);
		level.setCountAlienCorvette(1);
		level.setCountAlienDestroyer(9);
		level.setCountAlienFrigate(12);
		level.setCountAlienLightCruiser(4);
		level.setCountAlienHeavyCruiser(1);
		level.setCountAlienBattleCruiser(4);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(13);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.ANTARES);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Antares");
		level.setPositionX(0.2532353f);
		level.setPositionY(0.3548015f);
		level.setEarth(false);
		level.setCountAlienKamikaze(5);
		level.setCountAlienFighter(10);
		level.setCountAlienCorvette(6);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(6);
		level.setCountAlienLightCruiser(8);
		level.setCountAlienHeavyCruiser(12);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(10);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.POLLUX);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Pollux");
		level.setPositionX(0.084f);
		level.setPositionY(0.30625814f);
		level.setEarth(false);
		level.setCountAlienKamikaze(7);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(4);
		level.setCountAlienDestroyer(7);
		level.setCountAlienFrigate(9);
		level.setCountAlienLightCruiser(13);
		level.setCountAlienHeavyCruiser(7);
		level.setCountAlienBattleCruiser(9);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(3);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.DENEB);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Deneb");
		level.setPositionX(0.21308707f);
		level.setPositionY(0.25202563f);
		level.setEarth(false);
		level.setCountAlienKamikaze(5);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(3);
		level.setCountAlienDestroyer(13);
		level.setCountAlienFrigate(2);
		level.setCountAlienLightCruiser(5);
		level.setCountAlienHeavyCruiser(4);
		level.setCountAlienBattleCruiser(6);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(8);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.ALRAI);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Alrai");
		level.setPositionX(0.7066874f);
		level.setPositionY(0.63417155f);
		level.setEarth(false);
		level.setCountAlienKamikaze(1);
		level.setCountAlienFighter(14);
		level.setCountAlienCorvette(6);
		level.setCountAlienDestroyer(4);
		level.setCountAlienFrigate(7);
		level.setCountAlienLightCruiser(2);
		level.setCountAlienHeavyCruiser(13);
		level.setCountAlienBattleCruiser(6);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(8);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.TURAIS);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Turais");
		level.setPositionX(0.38255906f);
		level.setPositionY(0.3773528f);
		level.setEarth(false);
		level.setCountAlienKamikaze(0);
		level.setCountAlienFighter(2);
		level.setCountAlienCorvette(1);
		level.setCountAlienDestroyer(1);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(1);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(10);
		level.setCountAlienBattleShip(15);
		level.setCountAlienDreadnought(15);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.ARCTURUS);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Arcturus");
		level.setPositionX(0.3651323f);
		level.setPositionY(0.4477405f);
		level.setEarth(false);
		level.setCountAlienKamikaze(1);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(4);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(5);
		level.setCountAlienBattleCruiser(10);
		level.setCountAlienBattleShip(10);
		level.setCountAlienDreadnought(10);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.BELLATRIX);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Bellatrix");
		level.setPositionX(0.54473275f);
		level.setPositionY(0.3491878f);
		level.setEarth(false);
		level.setCountAlienKamikaze(20);
		level.setCountAlienFighter(0);
		level.setCountAlienCorvette(1);
		level.setCountAlienDestroyer(0);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(1);
		level.setCountAlienBattleCruiser(0);
		level.setCountAlienBattleShip(5);
		level.setCountAlienDreadnought(15);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.CASTOR);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Castor");
		level.setPositionX(0.46750432f);
		level.setPositionY(0.48376873f);
		level.setEarth(false);
		level.setCountAlienKamikaze(10);
		level.setCountAlienFighter(1);
		level.setCountAlienCorvette(10);
		level.setCountAlienDestroyer(1);
		level.setCountAlienFrigate(2);
		level.setCountAlienLightCruiser(1);
		level.setCountAlienHeavyCruiser(1);
		level.setCountAlienBattleCruiser(15);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(15);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.ELECTRA);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Electra");
		level.setPositionX(0.29156035f);
		level.setPositionY(0.31373027f);
		level.setEarth(false);
		level.setCountAlienKamikaze(7);
		level.setCountAlienFighter(1);
		level.setCountAlienCorvette(8);
		level.setCountAlienDestroyer(3);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(8);
		level.setCountAlienHeavyCruiser(0);
		level.setCountAlienBattleCruiser(10);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(10);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.KEID);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Keid");
		level.setPositionX(0.56656915f);
		level.setPositionY(0.4847785f);
		level.setEarth(false);
		level.setCountAlienKamikaze(6);
		level.setCountAlienFighter(5);
		level.setCountAlienCorvette(5);
		level.setCountAlienDestroyer(1);
		level.setCountAlienFrigate(4);
		level.setCountAlienLightCruiser(5);
		level.setCountAlienHeavyCruiser(5);
		level.setCountAlienBattleCruiser(9);
		level.setCountAlienBattleShip(5);
		level.setCountAlienDreadnought(13);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.SHARATAN);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Sharatan");
		level.setPositionX(0.19104148f);
		level.setPositionY(0.34279937f);
		level.setEarth(false);
		level.setCountAlienKamikaze(10);
		level.setCountAlienFighter(8);
		level.setCountAlienCorvette(9);
		level.setCountAlienDestroyer(8);
		level.setCountAlienFrigate(3);
		level.setCountAlienLightCruiser(2);
		level.setCountAlienHeavyCruiser(5);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(4);
		level.setCountAlienDreadnought(6);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.REGULUS);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Regulus");
		level.setPositionX(0.43552038f);
		level.setPositionY(0.4253224f);
		level.setEarth(false);
		level.setCountAlienKamikaze(13);
		level.setCountAlienFighter(4);
		level.setCountAlienCorvette(2);
		level.setCountAlienDestroyer(7);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(7);
		level.setCountAlienHeavyCruiser(14);
		level.setCountAlienBattleCruiser(5);
		level.setCountAlienBattleShip(0);
		level.setCountAlienDreadnought(2);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.MIMOSA);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Mimosa");
		level.setPositionX(0.33987814f);
		level.setPositionY(0.35118496f);
		level.setEarth(false);
		level.setCountAlienKamikaze(2);
		level.setCountAlienFighter(1);
		level.setCountAlienCorvette(1);
		level.setCountAlienDestroyer(5);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(1);
		level.setCountAlienHeavyCruiser(11);
		level.setCountAlienBattleCruiser(9);
		level.setCountAlienBattleShip(10);
		level.setCountAlienDreadnought(6);
		levels.add(level);
		
		level = new Level();
		level.setLevelName(LevelName.WEZEN);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Wezen");
		level.setPositionX(0.27185795f);
		level.setPositionY(0.43369076f);
		level.setEarth(false);
		level.setCountAlienKamikaze(2);
		level.setCountAlienFighter(2);
		level.setCountAlienCorvette(7);
		level.setCountAlienDestroyer(5);
		level.setCountAlienFrigate(3);
		level.setCountAlienLightCruiser(0);
		level.setCountAlienHeavyCruiser(9);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(5);
		level.setCountAlienDreadnought(6);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.PISCES);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Pisces");
		level.setPositionX(0.33053306f);
		level.setPositionY(0.24620555f);
		level.setEarth(false);
		level.setCountAlienKamikaze(5);
		level.setCountAlienFighter(4);
		level.setCountAlienCorvette(2);
		level.setCountAlienDestroyer(1);
		level.setCountAlienFrigate(3);
		level.setCountAlienLightCruiser(10);
		level.setCountAlienHeavyCruiser(4);
		level.setCountAlienBattleCruiser(6);
		level.setCountAlienBattleShip(5);
		level.setCountAlienDreadnought(7);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.ARIES);
		level.setLevelName(LevelName.ARIES);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Aries");
		level.setPositionX(0.47047108f);
		level.setPositionY(0.358602f);
		level.setEarth(false);
		level.setCountAlienKamikaze(1);
		level.setCountAlienFighter(1);
		level.setCountAlienCorvette(1);
		level.setCountAlienDestroyer(1);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(1);
		level.setCountAlienHeavyCruiser(1);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(20);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.FURUD);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Furud");
		level.setPositionX(0.38124385f);
		level.setPositionY(0.5022986f);
		level.setEarth(false);
		level.setCountAlienKamikaze(11);
		level.setCountAlienFighter(6);
		level.setCountAlienCorvette(3);
		level.setCountAlienDestroyer(5);
		level.setCountAlienFrigate(0);
		level.setCountAlienLightCruiser(1);
		level.setCountAlienHeavyCruiser(5);
		level.setCountAlienBattleCruiser(1);
		level.setCountAlienBattleShip(4);
		level.setCountAlienDreadnought(5);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.NUSAKAN);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Nusakan");
		level.setPositionX(0.6227367f);
		level.setPositionY(0.6348217f);
		level.setEarth(false);
		level.setCountAlienKamikaze(10);
		level.setCountAlienFighter(2);
		level.setCountAlienCorvette(4);
		level.setCountAlienDestroyer(7);
		level.setCountAlienFrigate(7);
		level.setCountAlienLightCruiser(1);
		level.setCountAlienHeavyCruiser(10);
		level.setCountAlienBattleCruiser(10);
		level.setCountAlienBattleShip(2);
		level.setCountAlienDreadnought(7);
		levels.add(level);

		level = new Level();
		level.setLevelName(LevelName.MINKAR);
		level.setDifficulty(Difficulty.HARD);
		level.setName("Minkar");
		level.setPositionX(0.13288797f);
		level.setPositionY(0.2876992f);
		level.setEarth(false);
		level.setCountAlienKamikaze(2);
		level.setCountAlienFighter(2);
		level.setCountAlienCorvette(1);
		level.setCountAlienDestroyer(1);
		level.setCountAlienFrigate(1);
		level.setCountAlienLightCruiser(14);
		level.setCountAlienHeavyCruiser(14);
		level.setCountAlienBattleCruiser(12);
		level.setCountAlienBattleShip(1);
		level.setCountAlienDreadnought(7);
		levels.add(level);	
	}

	public void loseLevel() {
		for(Level l: levels){
			if(l.isEarth()) continue;
			if(!Player.getInstance().isLevelAlien(l)){
				Player.getInstance().saveLevel(l, true);
				break;
			}
		}
		
	}
}
